# 2019-04-16 (martes)

### Anuncios
- Mañana empieza Lab4. Entrega viernes 26

- Leer Capítulo 1 de "Fundamentals of Database Systems" de Elmasri y Navathe.

### Hoy:
- Pandas

### Bases de Datos en Python

Ya trabajamos con algunas estructuras de datos básicas en python (listas, tuplas, diccionarios), y también aprendimos a crear nuestras propias estructuras de datos (objetos). 

Existen un tipo de estructura de datos a la que estamos muy acostumbrados, que llamamos coloquialmente "base de datos". Estos objetos usualmente tienen disponibles, **para los usuarios de los datos**, las siguientes operaciones:

- Creación de nuevas columnas ("variables")
- Análisis de subconjuntos de datos (por ej, "filtros" en Excel)
- Tablas resúmen (por ej, "Tabla dinámica" en Excel -- "collapse" en Stata)
- Cruce de datos (por ej, "buscarv" o "buscarh" de Excel)
- Union de bases de datos ("append" de Stata)

Para lo anterior, existe una librería muy potente de Python llamada "Pandas".

### Ejercicio en clase
Contemos el número de transacciones por fecha...

In [1]:
#cargamos datos del ejercicio

path = r'C:\Users\carlo\GIT_EAE253B\eae253b\Clases\clase11_20190416/transactions_small.csv'

file = open(path)

header = file.readline()

i = 0
dicc_fechas = {}

for line in file:
    i = i + 1
        
    rid,chain,dept,category,company,brand,fecha,productsize,productmeasure,purchasequantity,purchaseamount = line.strip().split(',')

    dicc_fechas[fecha] = dicc_fechas.get(fecha, 0) + 1 


#guardo las transacciones por fecha

lista_transacciones = []

for fecha, val in dicc_fechas.items():
    
    lista_transacciones.append((fecha, val))

print(lista_transacciones)

[('2012-12-11', 143), ('2012-04-02', 244), ('2012-10-21', 329), ('2012-08-23', 173), ('2012-10-07', 289), ('2013-06-24', 31), ('2012-03-23', 203), ('2012-04-26', 159), ('2013-06-18', 92), ('2012-11-22', 122), ('2012-09-27', 155), ('2012-05-18', 208), ('2012-10-11', 172), ('2012-11-07', 222), ('2012-06-08', 224), ('2013-04-03', 186), ('2012-08-08', 197), ('2013-03-01', 266), ('2013-06-07', 91), ('2013-03-26', 192), ('2013-03-31', 190), ('2012-05-29', 170), ('2012-03-22', 140), ('2012-09-13', 168), ('2013-05-24', 99), ('2013-04-27', 123), ('2013-06-13', 106), ('2013-01-04', 270), ('2013-07-01', 10), ('2012-07-04', 212), ('2012-06-28', 162), ('2013-01-27', 312), ('2013-07-12', 49), ('2012-09-18', 149), ('2012-04-27', 221), ('2012-04-09', 159), ('2012-04-20', 210), ('2013-02-06', 167), ('2012-06-20', 159), ('2012-09-26', 123), ('2013-04-28', 214), ('2012-08-17', 204), ('2012-06-05', 160), ('2013-03-30', 284), ('2012-09-14', 225), ('2012-10-10', 160), ('2013-07-17', 16), ('2013-04-14', 305), ('2013-01-02', 217), ('2012-09-29', 301), ('2012-06-26', 156), ('2012-03-13', 150), ('2013-03-19', 235), ('2012-03-29', 153), ('2012-09-28', 252), ('2013-03-15', 298), ('2012-10-29', 240), ('2013-07-09', 24), ('2012-05-04', 280), ('2012-11-11', 314), ('2013-06-15', 116), ('2012-12-06', 159), ('2012-04-23', 178), ('2013-05-31', 125), ('2012-12-26', 146), ('2012-05-10', 168), ('2012-05-16', 166), ('2012-10-27', 304), ('2013-01-20', 283), ('2013-05-12', 126), ('2013-01-18', 258), ('2012-09-05', 148), ('2013-02-20', 240), ('2012-10-09', 173), ('2012-12-31', 302), ('2012-11-01', 190), ('2013-05-27', 118), ('2013-01-01', 160), ('2013-06-04', 111), ('2013-06-21', 69), ('2012-07-07', 244), ('2012-04-21', 207), ('2012-03-03', 231), ('2012-07-14', 235), ('2013-03-04', 363), ('2012-07-03', 245), ('2013-06-08', 138), ('2012-10-18', 155), ('2012-12-29', 279), ('2012-04-28', 269), ('2012-09-07', 171), ('2013-06-25', 26), ('2013-07-16', 33), ('2013-04-17', 128), ('2013-05-10', 136), ('2012-06-19', 137), ('2013-02-17', 317), ('2013-07-22', 13), ('2012-08-26', 275), ('2013-05-19', 140), ('2012-08-02', 158), ('2012-07-11', 178), ('2012-10-13', 324), ('2012-06-18', 184), ('2012-04-18', 170), ('2012-04-19', 170), ('2012-06-21', 146), ('2013-06-23', 60), ('2012-07-05', 165), ('2012-07-19', 185), ('2013-01-06', 342), ('2013-05-28', 80), ('2013-01-03', 198), ('2012-05-03', 165), ('2012-11-08', 136), ('2013-07-19', 18), ('2013-01-30', 176), ('2012-10-02', 151), ('2012-09-09', 303), ('2013-07-11', 19), ('2012-12-01', 276), ('2012-08-21', 138), ('2013-02-26', 193), ('2013-01-31', 197), ('2012-04-08', 213), ('2012-05-23', 160), ('2012-07-25', 148), ('2012-05-07', 191), ('2012-06-23', 262), ('2013-03-08', 270), ('2012-12-13', 199), ('2012-08-10', 210), ('2012-05-31', 158), ('2012-05-20', 260), ('2013-04-15', 148), ('2012-09-30', 318), ('2012-10-15', 209), ('2013-06-29', 31), ('2013-04-12', 184), ('2012-08-25', 276), ('2012-03-11', 262), ('2012-05-08', 164), ('2012-03-21', 164), ('2013-02-11', 216), ('2013-01-08', 157), ('2012-12-03', 225), ('2013-05-30', 108), ('2012-08-05', 314), ('2012-07-15', 268), ('2013-02-24', 353), ('2012-10-05', 253), ('2012-05-21', 184), ('2012-07-02', 216), ('2012-08-16', 208), ('2013-04-13', 223), ('2013-04-09', 145), ('2013-05-23', 80), ('2013-04-11', 132), ('2012-09-19', 192), ('2013-01-10', 176), ('2012-07-10', 166), ('2012-04-29', 273), ('2012-12-14', 265), ('2013-07-05', 32), ('2012-04-10', 174), ('2012-03-09', 215), ('2012-11-02', 222), ('2012-04-14', 226), ('2013-07-06', 57), ('2013-05-04', 228), ('2012-11-24', 206), ('2012-04-25', 121), ('2012-05-17', 165), ('2012-08-28', 158), ('2013-03-28', 150), ('2012-08-30', 166), ('2013-05-15', 58), ('2012-10-26', 223), ('2012-05-12', 267), ('2012-09-22', 255), ('2013-06-16', 132), ('2012-08-19', 270), ('2012-03-24', 253), ('2013-03-18', 254), ('2012-03-30', 248), ('2012-12-08', 311), ('2013-03-22', 310), ('2012-07-13', 196), ('2013-04-23', 137), ('2012-05-02', 166), ('2012-09-03', 267), ('2013-02-23', 308), ('2012-12-25', 57), ('2013-02-07', 179), ('2012-10-25', 163), ('2013-06-10', 142), ('2012-10-30', 189), ('2012-04-04', 193), ('2013-06-02', 148), ('2013-06-12', 96), ('2013-05-26', 119), ('2012-07-17', 130), ('2013-01-26', 298), ('2012-06-17', 294), ('2013-05-07', 103), ('2013-02-01', 275), ('2013-03-09', 354), ('2012-09-06', 221), ('2013-04-04', 190), ('2012-09-25', 216), ('2012-07-06', 192), ('2013-02-22', 215), ('2013-04-25', 77), ('2012-10-08', 225), ('2012-11-28', 212), ('2012-11-04', 353), ('2013-01-29', 142), ('2013-03-13', 223), ('2012-10-12', 212), ('2012-03-17', 228), ('2013-07-20', 46), ('2013-03-10', 410), ('2013-04-26', 184), ('2012-11-17', 351), ('2012-03-12', 170), ('2013-01-14', 181), ('2012-12-24', 275), ('2012-07-31', 166), ('2012-09-15', 270), ('2012-11-12', 250), ('2012-03-04', 316), ('2013-01-19', 344), ('2013-07-13', 15), ('2012-10-03', 240), ('2012-10-31', 178), ('2012-10-22', 165), ('2013-01-16', 213), ('2012-03-02', 256), ('2012-11-25', 278), ('2012-06-30', 272), ('2012-08-15', 177), ('2013-02-12', 216), ('2013-06-28', 13), ('2012-09-17', 216), ('2012-06-03', 313), ('2013-03-02', 317), ('2013-04-02', 136), ('2012-10-28', 362), ('2013-05-18', 106), ('2013-02-08', 233), ('2013-02-13', 187), ('2012-12-16', 325), ('2013-02-28', 200), ('2013-06-14', 97), ('2013-04-05', 176), ('2012-06-04', 178), ('2013-03-24', 435), ('2013-07-10', 22), ('2013-04-22', 121), ('2013-02-21', 153), ('2012-11-09', 190), ('2012-03-06', 163), ('2012-06-14', 164), ('2012-04-05', 189), ('2013-04-29', 85), ('2012-12-07', 249), ('2012-08-24', 245), ('2013-05-05', 196), ('2012-08-20', 193), ('2012-07-16', 211), ('2013-05-08', 121), ('2012-05-01', 185), ('2012-05-30', 184), ('2013-01-07', 231), ('2012-09-12', 163), ('2012-07-24', 169), ('2013-03-27', 173), ('2013-02-10', 308), ('2012-11-06', 198), ('2013-02-05', 180), ('2013-04-24', 113), ('2012-06-09', 298), ('2013-01-28', 171), ('2012-11-29', 183), ('2013-05-14', 78), ('2012-06-15', 291), ('2013-05-20', 91), ('2012-09-02', 280), ('2012-09-16', 308), ('2012-12-21', 310), ('2012-11-15', 202), ('2013-05-22', 47), ('2012-12-05', 202), ('2012-10-01', 193), ('2012-07-09', 202), ('2012-05-06', 331), ('2012-07-12', 180), ('2013-02-16', 251), ('2012-07-27', 230), ('2012-10-16', 202), ('2012-09-08', 284), ('2012-08-07', 178), ('2012-03-28', 172), ('2012-06-06', 158), ('2012-03-15', 183), ('2013-03-29', 207), ('2013-02-04', 169), ('2012-11-30', 208), ('2012-05-27', 247), ('2013-04-18', 135), ('2012-04-24', 198), ('2012-08-14', 170), ('2013-02-03', 380), ('2012-03-18', 305), ('2012-12-28', 205), ('2013-02-15', 242), ('2012-04-30', 212), ('2012-11-14', 197), ('2012-05-09', 167), ('2012-06-25', 164), ('2012-05-15', 164), ('2013-05-16', 96), ('2013-04-21', 222), ('2012-10-14', 349), ('2013-07-02', 39), ('2012-09-10', 207), ('2013-03-07', 311), ('2013-03-17', 416), ('2013-04-06', 220), ('2012-12-17', 235), ('2012-12-23', 378), ('2013-03-12', 272), ('2012-03-26', 163), ('2013-05-01', 102), ('2012-07-22', 240), ('2012-06-01', 251), ('2012-07-01', 240), ('2012-07-21', 212), ('2013-01-15', 142), ('2012-11-26', 197), ('2013-03-23', 406), ('2012-06-10', 280), ('2013-06-03', 93), ('2012-11-23', 134), ('2012-07-26', 195), ('2013-01-05', 306), ('2013-06-30', 39), ('2012-10-04', 253), ('2012-11-13', 189), ('2012-12-09', 336), ('2012-03-20', 141), ('2013-01-17', 154), ('2012-11-19', 222), ('2012-09-23', 350), ('2012-12-22', 333), ('2013-03-06', 218), ('2012-12-10', 219), ('2013-07-08', 18), ('2013-07-03', 24), ('2013-06-01', 96), ('2012-10-23', 139), ('2012-09-20', 164), ('2012-04-16', 195), ('2012-06-13', 182), ('2012-06-27', 173), ('2012-10-06', 257), ('2012-09-04', 183), ('2012-04-15', 301), ('2012-03-07', 138), ('2012-08-29', 203), ('2012-09-21', 257), ('2012-12-18', 177), ('2012-08-18', 316), ('2013-04-20', 218), ('2012-08-27', 177), ('2013-07-21', 17), ('2012-08-09', 212), ('2012-07-30', 158), ('2013-03-11', 265), ('2012-08-13', 176), ('2013-06-09', 129), ('2012-07-18', 141), ('2012-04-03', 175), ('2012-08-11', 264), ('2012-07-29', 248), ('2013-06-19', 75), ('2012-06-12', 154), ('2013-01-23', 239), ('2013-06-22', 39), ('2012-08-04', 244), ('2013-05-13', 83), ('2012-11-21', 275), ('2012-11-18', 317), ('2012-11-03', 317), ('2012-12-30', 254), ('2012-04-22', 282), ('2013-03-16', 391), ('2013-05-17', 125), ('2013-07-18', 17), ('2013-06-17', 102), ('2012-05-22', 166), ('2012-07-08', 286), ('2013-03-05', 227), ('2012-05-28', 263), ('2013-02-02', 378), ('2013-01-13', 366), ('2012-11-05', 181), ('2012-11-27', 173), ('2012-05-26', 258), ('2012-05-19', 207), ('2012-11-16', 269), ('2013-04-16', 175), ('2012-05-13', 255), ('2012-03-27', 168), ('2012-05-25', 233), ('2013-03-03', 376), ('2012-03-10', 293), ('2013-01-09', 194), ('2012-07-28', 259), ('2012-03-08', 180), ('2013-01-21', 154), ('2013-05-25', 94), ('2012-10-17', 173), ('2012-03-25', 260), ('2012-08-12', 257), ('2013-02-27', 172), ('2012-10-19', 219), ('2012-12-27', 148), ('2012-03-16', 241), ('2013-01-12', 296), ('2012-04-12', 157), ('2012-06-29', 258), ('2012-09-01', 280), ('2013-04-01', 196), ('2012-03-31', 233), ('2013-05-09', 112), ('2013-02-14', 154), ('2013-01-25', 249), ('2012-04-11', 156), ('2013-05-29', 67), ('2013-07-15', 16), ('2013-06-26', 21), ('2013-06-06', 91), ('2013-05-03', 115), ('2013-02-25', 191), ('2012-06-07', 147), ('2013-03-14', 223), ('2012-12-02', 378), ('2012-04-06', 263), ('2012-05-11', 196), ('2012-11-10', 291), ('2012-06-16', 266), ('2013-06-20', 13), ('2013-04-10', 166), ('2012-12-12', 153), ('2013-04-08', 137), ('2012-09-11', 173), ('2013-04-30', 124), ('2013-05-02', 130), ('2012-05-24', 210), ('2013-02-19', 164), ('2012-04-13', 163), ('2012-08-03', 260), ('2013-01-22', 154), ('2013-07-07', 28), ('2012-06-02', 303), ('2013-07-14', 15), ('2012-03-14', 142), ('2012-04-01', 278), ('2012-08-31', 285), ('2013-02-09', 289), ('2012-11-20', 269), ('2012-12-15', 318), ('2012-12-20', 161), ('2013-01-11', 231), ('2012-06-24', 251), ('2012-08-22', 150), ('2013-01-24', 159), ('2012-04-07', 356), ('2012-08-06', 172), ('2012-12-19', 200), ('2012-07-20', 200), ('2012-06-22', 253), ('2013-07-23', 23), ('2013-05-11', 187), ('2013-02-18', 216), ('2012-12-04', 165), ('2012-10-24', 202), ('2012-03-05', 203), ('2013-06-27', 36), ('2013-07-04', 27), ('2012-10-20', 281), ('2012-07-23', 159), ('2012-08-01', 137), ('2012-05-05', 260), ('2012-06-11', 227), ('2013-05-21', 93), ('2013-06-05', 91), ('2013-04-07', 292), ('2013-06-11', 77), ('2012-05-14', 200), ('2013-03-21', 272), ('2012-04-17', 154), ('2013-04-19', 178), ('2013-03-25', 229), ('2013-05-06', 128), ('2012-09-24', 159), ('2012-03-19', 171), ('2013-03-20', 299)]

In [2]:
fecha_interes = '2012-03-11'

i = 0
for (fecha, num_trans) in lista_transacciones:
    i += 1
    if fecha == fecha_interes:
        print(num_trans)
        break

print('hice {} iteraciones'.format(i))

262
hice 141 iteraciones

Y si ocupamos pandas??

In [5]:
import pandas as pd

path = r'C:\Users\carlo\GIT_EAE253B\eae253b\Clases\clase11_20190416/transactions_small.csv'

df = pd.read_csv(path)

In [ ]:
from IPython.display import display

display(df)

In [6]:
df.groupby('date').count()

,id,chain,dept,category,company,brand,productsize,productmeasure,purchasequantity,purchaseamount
date,,,,,,,,,,
2012-03-02,256,256,256,256,256,256,256,254,256,256
2012-03-03,231,231,231,231,231,231,231,224,231,231
2012-03-04,316,316,316,316,316,316,316,306,316,316
2012-03-05,203,203,203,203,203,203,203,200,203,203
2012-03-06,163,163,163,163,163,163,163,162,163,163
2012-03-07,138,138,138,138,138,138,138,135,138,138
2012-03-08,180,180,180,180,180,180,180,178,180,180
2012-03-09,215,215,215,215,215,215,215,210,215,215
2012-03-10,293,293,293,293,293,293,293,288,293,293
2012-03-11,262,262,262,262,262,262,262,260,262,262
2012-03-12,170,170,170,170,170,170,170,168,170,170
2012-03-13,150,150,150,150,150,150,150,149,150,150
2012-03-14,142,142,142,142,142,142,142,142,142,142
2012-03-15,183,183,183,183,183,183,183,178,183,183
2012-03-16,241,241,241,241,241,241,241,235,241,241
2012-03-17,228,228,228,228,228,228,228,221,228,228
2012-03-18,305,305,305,305,305,305,305,300,305,305
2012-03-19,171,171,171,171,171,171,171,171,171,171
2012-03-20,141,141,141,141,141,141,141,138,141,141
2012-03-21,164,164,164,164,164,164,164,162,164,164
2012-03-22,140,140,140,140,140,140,140,137,140,140
2012-03-23,203,203,203,203,203,203,203,202,203,203
2012-03-24,253,253,253,253,253,253,253,244,253,253
2012-03-25,260,260,260,260,260,260,260,255,260,260
2012-03-26,163,163,163,163,163,163,163,162,163,163
2012-03-27,168,168,168,168,168,168,168,167,168,168
2012-03-28,172,172,172,172,172,172,172,169,172,172
2012-03-29,153,153,153,153,153,153,153,151,153,153
2012-03-30,248,248,248,248,248,248,248,245,248,248
2012-03-31,233,233,233,233,233,233,233,228,233,233
...,...,...,...,...,...,...,...,...,...,...
2013-06-24,31,31,31,31,31,31,31,30,31,31
2013-06-25,26,26,26,26,26,26,26,26,26,26
2013-06-26,21,21,21,21,21,21,21,21,21,21
2013-06-27,36,36,36,36,36,36,36,36,36,36
2013-06-28,13,13,13,13,13,13,13,13,13,13
2013-06-29,31,31,31,31,31,31,31,31,31,31
2013-06-30,39,39,39,39,39,39,39,39,39,39
2013-07-01,10,10,10,10,10,10,10,10,10,10
2013-07-02,39,39,39,39,39,39,39,39,39,39
2013-07-03,24,24,24,24,24,24,24,24,24,24
2013-07-04,27,27,27,27,27,27,27,27,27,27
2013-07-05,32,32,32,32,32,32,32,32,32,32
2013-07-06,57,57,57,57,57,57,57,56,57,57
2013-07-07,28,28,28,28,28,28,28,28,28,28
2013-07-08,18,18,18,18,18,18,18,18,18,18
2013-07-09,24,24,24,24,24,24,24,23,24,24
2013-07-10,22,22,22,22,22,22,22,22,22,22
2013-07-11,19,19,19,19,19,19,19,19,19,19
2013-07-12,49,49,49,49,49,49,49,48,49,49
2013-07-13,15,15,15,15,15,15,15,15,15,15
2013-07-14,15,15,15,15,15,15,15,14,15,15
2013-07-15,16,16,16,16,16,16,16,15,16,16
2013-07-16,33,33,33,33,33,33,33,33,33,33
2013-07-17,16,16,16,16,16,16,16,16,16,16
2013-07-18,17,17,17,17,17,17,17,17,17,17
2013-07-19,18,18,18,18,18,18,18,17,18,18
2013-07-20,46,46,46,46,46,46,46,45,46,46
2013-07-21,17,17,17,17,17,17,17,17,17,17
2013-07-22,13,13,13,13,13,13,13,13,13,13
2013-07-23,23,23,23,23,23,23,23,22,23,23

In [7]:
datos_agrupados = df.groupby('date').count()

transacciones_por_fecha = datos_agrupados['id']

display(transacciones_por_fecha)

NameError: name 'display' is not defined

Graficar? No hay problema:

In [ ]:
#esta linea me permite graficar en el mismo notebook..
%matplotlib inline

transacciones_por_fecha.plot()

Exportar a Excel? No hay problema

In [ ]:
transacciones_por_fecha.to_excel('ventas_por_fecha.xlsx')

## Indices

Un elemento clave detrás de las bases de datos son los "indices". Es la forma que tienen las bases de datos de "buscar" la información de manera eficiente, permitiendo esto que las operaciones sobre la base de datos sea lo más rápido posible.

In [ ]:
tabla_por_fecha.index

In [ ]:
type(tabla_por_fecha)

Busquemos la fecha de forma "ineficiente"

In [3]:
def busca_fecha(fecha_a_buscar, lista_transacciones):
    '''
    Busca el número de transacciones para una fecha
    en particular
    '''
    
    for fecha, val in lista_transacciones:
        if fecha == fecha_a_buscar:
            return val

    return 0

In [4]:
fecha_a_buscar = '2013-07-16'

busca_fecha(fecha_a_buscar, lista_transacciones)

33

In [9]:
transacciones_por_fecha.loc[fecha_a_buscar]

33

In [11]:
#ventas del un dia particular

%timeit busca_fecha(fecha_a_buscar, lista_transacciones)

%timeit transacciones_por_fecha.loc[fecha_a_buscar]

%timeit dicc_fechas[fecha_a_buscar]

100000 loops, best of 3: 9.76 µs per loop
10000 loops, best of 3: 57.4 µs per loop
The slowest run took 23.37 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 118 ns per loop

## Detour: geopandas

Existe una librería complementaria a Pandas llamada "GeoPandas". Dicha librería nos permite hacer gráficos (y cálculos) sobre geometrías (por ejemplo, "mapas").

In [ ]:
#CORRER ESTO SOLO EN COLAB.RESEARCH

!apt-get -qq install libspatialindex-dev
!pip install -q pysal
!pip install -q Rtree
!pip install -q shapely
!pip install -q geopandas
!pip install -q descartes

import pandas as pd
import geopandas as gp

#mapa del mundo

world = gp.read_file(gp.datasets.get_path('naturalearth_lowres'))

world = world[world.continent != 'Antarctica']

world.plot();
world.head()

In [ ]:
ax = world.plot(column='pop_est', cmap='Purples', figsize=(20,20), linewidth=0.25, edgecolor='black')
ax.axis('off')