### 1ra parte

Lea los datos de transacciones de fondos y guarde la información en SQL. Podría ser útil ver:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html

In [6]:
#lee los datos desde excel
import pandas as pd

data = pd.read_excel('transacc.xlsx')


#guarda info a sql
import sqlite3
conn = sqlite3.connect('db_transacciones.db')
data.to_sql('transacciones', conn, if_exists='replace', index=False)

In [3]:
data

,PERIODO,R_INVERSIONISTA,R_TIPO_INVERSIONISTA,R_ACTIVO,R_TIPO_ACTIVO,R_NEMO_ACTIVO,DESTINO,R_MONTO_INVERSION
0,201812,19528,FI,12345,CFIPE,OTRO,FI_INV_EXTR,150705.276423
1,201812,19561,FI,12345,CFIE,OTRO,FI_INV_EXTR,156673.459268
2,201812,19593,FI,12345,CFIPE,OTRO,FI_INV_EXTR,277432.363821
3,201812,19621,FI,12345,CFIPE,OTRO,FI_INV_EXTR,598485.045366
4,201812,21515,FI,12345,CFIPE,OTRO,FI_INV_EXTR,172918.650488
5,201812,21530,FI,12345,CFIPE,OTRO,FI_INV_EXTR,322689.598049
6,201812,21561,FI,12345,CFIPE,OTRO,FI_INV_EXTR,213746.272927
7,201812,21659,FI,12345,CFIPE,OTRO,FI_INV_EXTR,439348.824146
8,201812,21704,FI,12345,CFIPE,OTRO,FI_INV_EXTR,313651.939512
9,201812,21783,FI,12345,CFIPE,OTRO,FI_INV_EXTR,61314.864634
10,201812,21787,FI,12345,CFIPE,OTRO,FI_INV_EXTR,82242.692683
11,201812,21964,FI,12345,OT,NUEVO CLP 29012019,FI_INV_NACI,2264.382114
12,201812,21446,FI,19355,CFI,CFIPIONERO,FI_INV_NACI,1223.130081
13,201812,19529,FI,19359,BE,BINDE-A,FI_INV_NACI,17483.601626
14,201812,19620,FI,19359,BE,BINDE-A,FI_INV_NACI,17140.788618
15,201812,20400,FM,19359,BE,BINDE-A,FFM_INV_NACI,17597.878049
16,201812,20434,FM,19359,BE,BINDE-A,FFM_INV_NACI,21711.666667
17,201812,20463,FM,19359,BE,BINDE-A,FFM_INV_NACI,66734.804878
18,201812,20548,FM,19359,BE,BINDE-A,FFM_INV_NACI,2971.073171
19,201812,20766,FM,19359,BE,BINDE-A,FFM_INV_NACI,13941.170732
20,201812,21151,FM,19359,BE,BINDE-A,FFM_INV_NACI,14741.065041
21,201812,21295,FM,19359,BE,BINDE-A,FFM_INV_NACI,11427.195122
22,201812,21351,FM,19359,CFI,CFINRENTAS,FFM_INV_NACI,1266.926829
23,201812,21378,FM,19359,BE,BINDE-A,FFM_INV_NACI,1142.715447
24,201812,21401,FM,19359,BE,BINDE-A,FFM_INV_NACI,3428.154472
25,201812,21444,FI,19359,BE,BINDE-A,FI_INV_NACI,4570.878049
26,201812,21446,FI,19359,CFI,CFINRENTAS,FI_INV_NACI,364.878049
27,201812,21462,FI,19359,BE,BINDE-A,FI_INV_NACI,9484.569106
28,201812,21498,FI,19359,BE,BINDE-A,FI_INV_NACI,9027.479675
29,201812,21596,FI,19359,BE,BINDE-A,FI_INV_NACI,11655.739837
...,...,...,...,...,...,...,...,...
39625,201812,22000,FM,NUSHYIU ID,CFME,NUSHYIU ID,FFM_INV_EXTR,4.227642
39626,201812,22000,FM,PIMINIA ID,CFME,PIMINIA ID,FFM_INV_EXTR,5.804878
39627,201812,22000,FM,VECMHIH LX,CFME,VECMHIH LX,FFM_INV_EXTR,2.902439
39628,201812,22000,FM,VONEMCX LX,CFME,VONEMCX LX,FFM_INV_EXTR,10.902439
39629,201812,22000,FM,ZODMUBA LX,CFME,ZODMUBA LX,FFM_INV_EXTR,2.048780
39630,201812,22006,FI,US9128284J61,BEBCE,US9128284J61,FI_INV_EXTR,8483.650407
39631,201812,22006,FI,US9128284Y39,BEBCE,US9128284Y39,FI_INV_EXTR,2852.439024
39632,201812,22006,FI,US912828F627,BEBCE,US912828F627,FI_INV_EXTR,8416.577236
39633,201812,22011,FI,SANHYDI LX,ETFA,SANHYDI LX,FI_INV_EXTR,46664.707317
39634,201812,22013,FI,CFIE ACPPD2U,CFIE,CFIE ACPPD2U,FI_INV_EXTR,26401.260000
39635,201812,22017,FM,XS1867930999,NEERV,XS1867930999,FFM_INV_EXTR,17742.845528
39636,201812,22018,FM,XS1836387933,NEERV,XS1836387933,FFM_INV_EXTR,28473.081301
39637,201812,22021,FI,SCHEMCA LX,CFME,SCHEMCA LX,FI_INV_EXTR,1090.167561
39638,201812,22021,FI,SCHECAC LX,CFME,SCHECAC LX,FI_INV_EXTR,4507.532195
39639,201812,22021,FI,VONFARJ LX,CFME,VONFARJ LX,FI_INV_EXTR,2835.565366
39640,201812,22021,FI,GUIASIA LX,CFME,GUIASIA LX,FI_INV_EXTR,3818.410732
39641,201812,22021,FI,MATAPTI LX,CFME,MATAPTI LX,FI_INV_EXTR,2925.941951
39642,201812,22021,FI,EWZ US,ETFA,EWZ US,FI_INV_EXTR,2208.577805
39643,201812,22021,FI,EZA US,ETFA,EZA US,FI_INV_EXTR,1508.159268
39644,201812,22021,FI,EWW US,ETFA,EWW US,FI_INV_EXTR,593.096341
39645,201812,22021,FI,EEM US,ETFA,EEM US,FI_INV_EXTR,5738.913171
39646,201812,22021,FI,ILF US,ETFA,ILF US,FI_INV_EXTR,1095.816098
39647,201812,22021,FI,AAXJ US,ETFA,AAXJ US,FI_INV_EXTR,8902.093659
39648,201812,22021,FI,ERUS US,ETFA,ERUS US,FI_INV_EXTR,316.318049
39649,201812,22022,FI,TRPGEBI LX,CFME,TRPGEBI LX,FI_INV_EXTR,12257.324390
39650,201812,22022,FI,TRPELMI LX,CFME,TRPELMI LX,FI_INV_EXTR,6168.201951
39651,201812,22022,FI,TRPEMCI LX,CFME,TRPEMCI LX,FI_INV_EXTR,12234.730244
39652,201812,22029,FI,CHILEANFEEDER,OTDNE,CHILEANFEEDER,FI_INV_EXTR,70990.807805
39653,201812,22039,FI,OTRO,OTROC,OTRO,FI_INV_EXTR,4066.946341
39654,201812,22040,FI,PRPRONOTE,OTROC,PRPRONOTE,FI_INV_EXTR,95313.406341

### 2da parte

A partir del archivo SQL, responda las siguientes preguntas:

    - ¿a cuántos períodos se refiere la información?

In [13]:
import pandas as pd

query = 'select distinct periodo from transacciones'

df = pd.read_sql(query, conn)
df

   PERIODO
0   201812

    - ¿cuántos inversionistas hay en la base?

In [18]:
query = '''
    SELECT COUNT(*)
    FROM 
    (
        select distinct r_inversionista 
        from transacciones
    )
'''

df = pd.read_sql(query, conn)
df

   COUNT(*)
0       859

- ¿cuántos activos hay en la base?

In [44]:
query = '''
    SELECT COUNT(*)
    FROM 
    (
        select distinct r_activo 
        from transacciones
    )
'''

df = pd.read_sql(query, conn)
df

   COUNT(*)
0      5868

    - ¿cuántos activos por tipo de activo hay en la base (R_TIPO_ACTIVO)?

In [43]:
param = 'BBFE'

query = '''
    SELECT r_tipo_activo, COUNT(*)
    FROM 
    (
        select distinct r_tipo_activo, r_activo 
        from transacciones
    )
    where r_tipo_activo = "{}"
    GROUP BY r_tipo_activo
'''.format(param)

data = conn.cursor().execute(query)

df = pd.DataFrame.from_records(data.fetchall())
df

Warning: You can only execute one statement at a time.

    - Monto total invertido por estos inversionistas

In [22]:
query = '''
    SELECT SUM(R_MONTO_INVERSION)
    FROM TRANSACCIONES
'''

df = pd.read_sql(query, conn)
df

   SUM(R_MONTO_INVERSION)
0            4.119507e+08

    - Monto total invertido por cada inversionista

In [25]:
query = '''
    SELECT R_INVERSIONISTA, SUM(R_MONTO_INVERSION)/ COUNT(*), AVG(R_MONTO_INVERSION)
    FROM TRANSACCIONES
    GROUP BY R_INVERSIONISTA
'''

df = pd.read_sql(query, conn)
df

     R_INVERSIONISTA  SUM(R_MONTO_INVERSION)/ COUNT(*)  AVG(R_MONTO_INVERSION)
0              19347                     105030.713189           105030.713189
1              19352                       1190.934959             1190.934959
2              19353                      29372.821138            29372.821138
3              19354                        935.243902              935.243902
4              19355                     217179.353659           217179.353659
5              19359                     390112.513211           390112.513211
6              19360                      68547.206844            68547.206844
7              19361                      47925.813008            47925.813008
8              19363                      81672.780488            81672.780488
9              19367                      57435.496516            57435.496516
10             19376                     115579.473303           115579.473303
11             19391                       5363.825203             5363.825203
12             19400                      45991.612821            45991.612821
13             19409                     191259.448780           191259.448780
14             19420                      13654.593496            13654.593496
15             19431                       1169.247073             1169.247073
16             19434                      53515.333914            53515.333914
17             19444                      21508.802461            21508.802461
18             19449                       4614.854390             4614.854390
19             19452                       4884.552846             4884.552846
20             19464                      38884.808491            38884.808491
21             19472                      37521.345691            37521.345691
22             19476                       2989.747967             2989.747967
23             19480                      23837.328724            23837.328724
24             19481                      43885.186285            43885.186285
25             19486                      27397.897019            27397.897019
26             19492                      35265.825124            35265.825124
27             19505                       5424.430894             5424.430894
28             19508                        163.807561              163.807561
29             19516                      16747.254169            16747.254169
..               ...                               ...                     ...
829            21983                       2982.048103             2982.048103
830            21984                     160492.024390           160492.024390
831            21985                       9382.674797             9382.674797
832            21986                       3740.871729             3740.871729
833            21991                       6720.995122             6720.995122
834            21992                      41337.526829            41337.526829
835            21993                       1498.844625             1498.844625
836            21994                      14464.863595            14464.863595
837            21996                         16.391495               16.391495
838            21997                      28338.708049            28338.708049
839            21998                      31823.855122            31823.855122
840            22000                          6.546483                6.546483
841            22003                      10983.753000            10983.753000
842            22006                       7729.328817             7729.328817
843            22010                      56848.032520            56848.032520
844            22011                      46664.707317            46664.707317
845            22013                      26401.260000            26401.260000
846            22017                      17742.845528            17742.845528
847            22018                      28473.081301            28473.081301
848            22020                      10438.824265            10438.824265
849            22021                       2961.716016             2961.716016
850            22022                      10220.085528            10220.085528
851            22029                      47988.083984            47988.083984
852            22035                       2418.589904             2418.589904
853            22036                       1671.611999             1671.611999
854            22037                        970.441965              970.441965
855            22038                       1178.933282             1178.933282
856            22039                       4066.946341             4066.946341
857            22040                      95313.406341            95313.406341
858            22044                       7979.561556             7979.561556

[859 rows x 3 columns]

    - Porcentaje que representa el monto invertido en cada activo, sobre el total invertido por cada inversionista

In [55]:
query = '''
    WITH TABLA_AUXILIAR AS (
        SELECT R_INVERSIONISTA, SUM(R_MONTO_INVERSION) AS MONTO_TOTAL
        FROM TRANSACCIONES
        GROUP BY R_INVERSIONISTA
    )
    
    SELECT *
    FROM TRANSACCIONES JOIN TABLA_AUXILIAR USING (R_INVERSIONISTA)
    ORDER BY R_INVERSIONISTA
'''

df = pd.read_sql(query, conn)

df['porcentaje'] = df['R_MONTO_INVERSION'] / df.MONTO_TOTAL

df

,PERIODO,R_INVERSIONISTA,R_TIPO_INVERSIONISTA,R_ACTIVO,R_TIPO_ACTIVO,R_NEMO_ACTIVO,DESTINO,R_MONTO_INVERSION,MONTO_TOTAL,porcentaje
0,201812,19347,FI,20452,CFM,CFMBCICPAP,FI_INV_NACI,4798.138211,1.890553e+06,0.002538
1,201812,19347,FI,61820345,PE,SUAGUA120325,FI_INV_NACI,342.878049,1.890553e+06,0.000181
2,201812,19347,FI,61820345,PE,SUAGUA220620,FI_INV_NACI,452.715447,1.890553e+06,0.000239
3,201812,19347,FI,76050597,OTDN,OUNU-310328,FI_INV_NACI,5528.650407,1.890553e+06,0.002924
4,201812,19347,FI,76141503,OTDN,ONPRO-011222,FI_INV_NACI,149842.487805,1.890553e+06,0.079259
5,201812,19347,FI,76141503,OTDN,OUPR-310328,FI_INV_NACI,219138.081301,1.890553e+06,0.115912
6,201812,19347,FI,76373801,OTDN,OUPA-310328,FI_INV_NACI,361305.780488,1.890553e+06,0.191111
7,201812,19347,FI,76832631,OTDN,ONTAM-011222,FI_INV_NACI,8610.853659,1.890553e+06,0.004555
8,201812,19347,FI,76832631,OTDN,OUTA-310328,FI_INV_NACI,11116.878049,1.890553e+06,0.005880
9,201812,19347,FI,96740685,OTDN,ONIND-011230,FI_INV_NACI,118868.463415,1.890553e+06,0.062875
10,201812,19347,FI,96740685,OTDN,OUIN-310328,FI_INV_NACI,280064.682927,1.890553e+06,0.148139
11,201812,19347,FI,96790465,OTDN,ONTO-310328,FI_INV_NACI,56751.463415,1.890553e+06,0.030018
12,201812,19347,FI,96838655,OTDN,OUCO-310328,FI_INV_NACI,1496.097561,1.890553e+06,0.000791
13,201812,19347,FI,96849485,OTDN,ONTA-310328,FI_INV_NACI,19924.268293,1.890553e+06,0.010539
14,201812,19347,FI,96910005,OTDN,OUBG-310328,FI_INV_NACI,10528.536585,1.890553e+06,0.005569
15,201812,19347,FI,97012105,OTDN,ONREC-011222,FI_INV_NACI,67780.886179,1.890553e+06,0.035852
16,201812,19347,FI,97012105,OTDN,OURE-310328,FI_INV_NACI,538006.780488,1.890553e+06,0.284576
17,201812,19347,FI,99611395,OTDN,OUTO-310328,FI_INV_NACI,35995.195122,1.890553e+06,0.019040
18,201812,19352,FI,20598,CFM,CFMSECPLUA,FI_INV_NACI,808.325203,3.572805e+03,0.226244
19,201812,19352,FI,20598,CFM,CFMSECPLUC,FI_INV_NACI,2348.926829,3.572805e+03,0.657446
20,201812,19352,FI,21367,CFM,CFMBCHCAPE,FI_INV_NACI,415.552846,3.572805e+03,0.116310
21,201812,19353,FI,OTRO,ACNE,OTRO,FI_INV_EXTR,29372.821138,2.937282e+04,1.000000
22,201812,19354,FI,97018345,DPC,FNBCI-030119,FI_INV_NACI,935.243902,9.352439e+02,1.000000
23,201812,19355,FI,76017394,ACC,EISA,FI_INV_NACI,130693.056911,7.384098e+06,0.017699
24,201812,19355,FI,76025021,ACC,SMU,FI_INV_NACI,146384.268293,7.384098e+06,0.019824
25,201812,19355,FI,76196413,ACC,NITRATOS,FI_INV_NACI,32676.422764,7.384098e+06,0.004425
26,201812,19355,FI,76209063,ACC,SMSAAM,FI_INV_NACI,382269.813008,7.384098e+06,0.051769
27,201812,19355,FI,76278939,ACC,TRICOT,FI_INV_NACI,161725.292683,7.384098e+06,0.021902
28,201812,19355,FI,80872745,ACC,BLUMAR,FI_INV_NACI,375687.414634,7.384098e+06,0.050878
29,201812,19355,FI,84369145,ACC,WATTS,FI_INV_NACI,494133.333333,7.384098e+06,0.066919
...,...,...,...,...,...,...,...,...,...,...
39625,201812,22038,FM,97048345,BB,BSTDED0114,FFM_INV_NACI,471.268293,7.427280e+04,0.006345
39626,201812,22038,FM,97048345,BB,BSTDP60315,FFM_INV_NACI,227.227642,7.427280e+04,0.003059
39627,201812,22038,FM,97048345,BB,BSTDR51215,FFM_INV_NACI,693.682927,7.427280e+04,0.009340
39628,201812,22038,FM,97048345,BB,BSTDSB0714,FFM_INV_NACI,2273.829268,7.427280e+04,0.030615
39629,201812,22038,FM,97048345,BB,BSTDSF1014,FFM_INV_NACI,229.186992,7.427280e+04,0.003086
39630,201812,22038,FM,97065345,BB,BSECB40615,FFM_INV_NACI,679.162602,7.427280e+04,0.009144
39631,201812,22038,FM,97065345,BB,BSECK31112,FFM_INV_NACI,119.292683,7.427280e+04,0.001606
39632,201812,22038,FM,97092345,DPC,FNBIC-020119,FFM_INV_NACI,178.837398,7.427280e+04,0.002408
39633,201812,22038,FM,97959345,BB,BRPL-K0315,FFM_INV_NACI,4334.414634,7.427280e+04,0.058358
39634,201812,22038,FM,97959345,BB,BRPL-N0717,FFM_INV_NACI,896.544715,7.427280e+04,0.012071
39635,201812,22038,FM,97959345,BB,BRPL-Q0618,FFM_INV_NACI,447.032520,7.427280e+04,0.006019
39636,201812,22038,FM,99512755,BB,BCNO-U0915,FFM_INV_NACI,456.536585,7.427280e+04,0.006147
39637,201812,22038,FM,99512755,BB,BCNOAB0317,FFM_INV_NACI,1381.211382,7.427280e+04,0.018596
39638,201812,22038,FM,99512755,BB,BCNOAP0318,FFM_INV_NACI,453.512195,7.427280e+04,0.006106
39639,201812,22039,FI,OTRO,OTROC,OTRO,FI_INV_EXTR,4066.946341,4.066946e+03,1.000000
39640,201812,22040,FI,PRPRONOTE,OTROC,PRPRONOTE,FI_INV_EXTR,95313.406341,9.531341e+04,1.000000
39641,201812,22044,FM,96522005,DPC,FNFAL-070119,FFM_INV_NACI,16251.439024,1.117139e+05,0.145474
39642,201812,22044,FM,96691135,BE,BFORU-AX,FFM_INV_NACI,666.861789,1.117139e+05,0.005969
39643,201812,22044,FM,97018345,DPC,FNBCI-020119,FFM_INV_NACI,20322.089431,1.117139e+05,0.181912
39644,201812,22044,FM,97030345,BB,BBBVP50316,FFM_INV_NACI,8677.398374,1.117139e+05,0.077675
39645,201812,22044,FM,97030345,DPC,FNBBV-020119,FFM_INV_NACI,12193.252033,1.117139e+05,0.109147
39646,201812,22044,FM,97035345,DPC,FNITA-020119,FFM_INV_NACI,2438.634146,1.117139e+05,0.021829
39647,201812,22044,FM,97035345,DPL,FNITA-081020,FFM_INV_NACI,3780.495935,1.117139e+05,0.033841
39648,201812,22044,FM,97041345,PDBC,BNPDBC030119,FFM_INV_NACI,9754.146341,1.117139e+05,0.087314
39649,201812,22044,FM,97041345,PDBC,BNPDBC040119,FFM_INV_NACI,731.504065,1.117139e+05,0.006548
39650,201812,22044,FM,97041345,PDBC,BNPDBC080119,FFM_INV_NACI,17876.642276,1.117139e+05,0.160022
39651,201812,22044,FM,97042345,DPC,FNEST-070119,FFM_INV_NACI,6094.292683,1.117139e+05,0.054553
39652,201812,22044,FM,97048345,BB,BSTDR40915,FFM_INV_NACI,8497.780488,1.117139e+05,0.076067
39653,201812,22044,FM,97065345,DPC,FNSEC-070119,FFM_INV_NACI,2437.772358,1.117139e+05,0.021822
39654,201812,22044,FM,99512755,DPC,FNCNO-020119,FFM_INV_NACI,1991.552846,1.117139e+05,0.017827

In [32]:
query = '''
    SELECT R_INVERSIONISTA, R_ACTIVO, R_MONTO_INVERSION, 
    MONTO_TOTAL, R_MONTO_INVERSION / MONTO_TOTAL AS PERC_MONTO
    FROM TRANSACCIONES JOIN   
        (SELECT R_INVERSIONISTA, SUM(R_MONTO_INVERSION) AS MONTO_TOTAL
        FROM TRANSACCIONES
        GROUP BY R_INVERSIONISTA) USING (R_INVERSIONISTA)
    WHERE R_INVERSIONISTA = ?
    ORDER BY R_INVERSIONISTA
'''

df = pd.read_sql(query, conn, params=(19347,))
df

    R_INVERSIONISTA  R_ACTIVO  R_MONTO_INVERSION   MONTO_TOTAL  PERC_MONTO
0             19347     20452        4798.138211  1.890553e+06    0.002538
1             19347  61820345         342.878049  1.890553e+06    0.000181
2             19347  61820345         452.715447  1.890553e+06    0.000239
3             19347  76050597        5528.650407  1.890553e+06    0.002924
4             19347  76141503      149842.487805  1.890553e+06    0.079259
5             19347  76141503      219138.081301  1.890553e+06    0.115912
6             19347  76373801      361305.780488  1.890553e+06    0.191111
7             19347  76832631        8610.853659  1.890553e+06    0.004555
8             19347  76832631       11116.878049  1.890553e+06    0.005880
9             19347  96740685      118868.463415  1.890553e+06    0.062875
10            19347  96740685      280064.682927  1.890553e+06    0.148139
11            19347  96790465       56751.463415  1.890553e+06    0.030018
12            19347  96838655        1496.097561  1.890553e+06    0.000791
13            19347  96849485       19924.268293  1.890553e+06    0.010539
14            19347  96910005       10528.536585  1.890553e+06    0.005569
15            19347  97012105       67780.886179  1.890553e+06    0.035852
16            19347  97012105      538006.780488  1.890553e+06    0.284576
17            19347  99611395       35995.195122  1.890553e+06    0.019040

    - Listado de inversionistas que invierten, en algún activo, más del 10% de su cartera.

In [75]:
#param = float(input())

query = '''
    WITH TABLA_AUXILIAR AS (
        SELECT R_INVERSIONISTA, SUM(R_MONTO_INVERSION) AS MONTO_TOTAL
        FROM TRANSACCIONES
        GROUP BY R_INVERSIONISTA
    ), 
    TABLA2 AS (
        SELECT R_INVERSIONISTA, R_ACTIVO, R_MONTO_INVERSION / MONTO_TOTAL AS PORCENTAJE
        FROM TRANSACCIONES JOIN TABLA_AUXILIAR USING (R_INVERSIONISTA)
        WHERE PORCENTAJE BETWEEN ? AND ?
        ORDER BY R_INVERSIONISTA    
    )
    
    SELECT DISTINCT R_INVERSIONISTA
    FROM TABLA2

'''

df = pd.read_sql(query, conn, params=[0.1,0.2])
df

     R_INVERSIONISTA
0              19347
1              19352
2              19359
3              19363
4              19367
5              19376
6              19434
7              19516
8              19530
9              19564
10             19569
11             19573
12             19581
13             19598
14             19599
15             19604
16             19615
17             19616
18             19623
19             19635
20             20377
21             20383
22             20388
23             20390
24             20397
25             20419
26             20422
27             20423
28             20433
29             20435
..               ...
281            21915
282            21916
283            21918
284            21920
285            21921
286            21922
287            21927
288            21931
289            21934
290            21938
291            21939
292            21941
293            21947
294            21951
295            21959
296            21965
297            21975
298            21976
299            21983
300            21986
301            21991
302            21992
303            21993
304            21996
305            22003
306            22006
307            22020
308            22021
309            22029
310            22044

[311 rows x 1 columns]

    - Listado de inversionistas que invierten, en algún activo, más del 10% de su cartera.

    - ¿qué tipo de inversionista (FM o FI) tiene una cartera de inversión más grande? Muestre el total, y también los montos desagregados por inversión extranjera e inversión nacional.
    - ¿qué tipos de activos tienen los mayores montos de inversión?


Finalmente, escriba código que le permita saber, de forma "dinámica", el total invertido (nacional y extranjero) por alguno de los tipos de inversionistas.


### 3ra parte

- Determine cuáles inversionistas son también activos.

In [78]:
#param = float(input())

query = '''
    WITH INVERSIONISTAS AS (
        SELECT DISTINCT R_INVERSIONISTA AS ID
        FROM TRANSACCIONES
    ), 
    ACTIVOS AS (    
        SELECT DISTINCT R_ACTIVO AS ID
        FROM TRANSACCIONES
    )
    
    SELECT *
    FROM INVERSIONISTAS INNER JOIN ACTIVOS USING (ID)
    
'''

df = pd.read_sql(query, conn)
df

        ID
0    19355
1    19359
2    19361
3    19400
4    19409
5    19434
6    19530
7    19555
8    19564
9    19569
10   19620
11   19623
12   19629
13   19640
14   20368
15   20371
16   20373
17   20374
18   20380
19   20381
20   20382
21   20383
22   20391
23   20394
24   20399
25   20400
26   20402
27   20403
28   20408
29   20409
..     ...
190  21805
191  21810
192  21817
193  21821
194  21825
195  21828
196  21834
197  21850
198  21853
199  21857
200  21867
201  21876
202  21878
203  21884
204  21895
205  21896
206  21898
207  21899
208  21902
209  21906
210  21920
211  21922
212  21926
213  21942
214  21945
215  21951
216  21961
217  21970
218  22003
219  22006

[220 rows x 1 columns]

In [ ]:
- ¿cómo podríamos saber los activos "subyacentes" de los inversionistas?

In [ ]:
query = '''
    select r_tipo_inversionista, count(*) 
    from transacciones 
    group by r_tipo_inversionista'''

In [14]:
import pandas as pd

data = pd.read_excel('transacc.xlsx')


import sqlite3

conn = sqlite3.connect('db_transacciones.db')

data.to_sql('transacciones', conn, if_exists='replace', index=False)

In [10]:
data

,PERIODO,R_INVERSIONISTA,R_TIPO_INVERSIONISTA,R_ACTIVO,R_TIPO_ACTIVO,R_NEMO_ACTIVO,DESTINO,R_MONTO_INVERSION
0,201812,19528,FI,12345,CFIPE,OTRO,FI_INV_EXTR,150705.276423
1,201812,19561,FI,12345,CFIE,OTRO,FI_INV_EXTR,156673.459268
2,201812,19593,FI,12345,CFIPE,OTRO,FI_INV_EXTR,277432.363821
3,201812,19621,FI,12345,CFIPE,OTRO,FI_INV_EXTR,598485.045366
4,201812,21515,FI,12345,CFIPE,OTRO,FI_INV_EXTR,172918.650488
5,201812,21530,FI,12345,CFIPE,OTRO,FI_INV_EXTR,322689.598049
6,201812,21561,FI,12345,CFIPE,OTRO,FI_INV_EXTR,213746.272927
7,201812,21659,FI,12345,CFIPE,OTRO,FI_INV_EXTR,439348.824146
8,201812,21704,FI,12345,CFIPE,OTRO,FI_INV_EXTR,313651.939512
9,201812,21783,FI,12345,CFIPE,OTRO,FI_INV_EXTR,61314.864634
10,201812,21787,FI,12345,CFIPE,OTRO,FI_INV_EXTR,82242.692683
11,201812,21964,FI,12345,OT,NUEVO CLP 29012019,FI_INV_NACI,2264.382114
12,201812,21446,FI,19355,CFI,CFIPIONERO,FI_INV_NACI,1223.130081
13,201812,19529,FI,19359,BE,BINDE-A,FI_INV_NACI,17483.601626
14,201812,19620,FI,19359,BE,BINDE-A,FI_INV_NACI,17140.788618
15,201812,20400,FM,19359,BE,BINDE-A,FFM_INV_NACI,17597.878049
16,201812,20434,FM,19359,BE,BINDE-A,FFM_INV_NACI,21711.666667
17,201812,20463,FM,19359,BE,BINDE-A,FFM_INV_NACI,66734.804878
18,201812,20548,FM,19359,BE,BINDE-A,FFM_INV_NACI,2971.073171
19,201812,20766,FM,19359,BE,BINDE-A,FFM_INV_NACI,13941.170732
20,201812,21151,FM,19359,BE,BINDE-A,FFM_INV_NACI,14741.065041
21,201812,21295,FM,19359,BE,BINDE-A,FFM_INV_NACI,11427.195122
22,201812,21351,FM,19359,CFI,CFINRENTAS,FFM_INV_NACI,1266.926829
23,201812,21378,FM,19359,BE,BINDE-A,FFM_INV_NACI,1142.715447
24,201812,21401,FM,19359,BE,BINDE-A,FFM_INV_NACI,3428.154472
25,201812,21444,FI,19359,BE,BINDE-A,FI_INV_NACI,4570.878049
26,201812,21446,FI,19359,CFI,CFINRENTAS,FI_INV_NACI,364.878049
27,201812,21462,FI,19359,BE,BINDE-A,FI_INV_NACI,9484.569106
28,201812,21498,FI,19359,BE,BINDE-A,FI_INV_NACI,9027.479675
29,201812,21596,FI,19359,BE,BINDE-A,FI_INV_NACI,11655.739837
...,...,...,...,...,...,...,...,...
39625,201812,22000,FM,NUSHYIU ID,CFME,NUSHYIU ID,FFM_INV_EXTR,4.227642
39626,201812,22000,FM,PIMINIA ID,CFME,PIMINIA ID,FFM_INV_EXTR,5.804878
39627,201812,22000,FM,VECMHIH LX,CFME,VECMHIH LX,FFM_INV_EXTR,2.902439
39628,201812,22000,FM,VONEMCX LX,CFME,VONEMCX LX,FFM_INV_EXTR,10.902439
39629,201812,22000,FM,ZODMUBA LX,CFME,ZODMUBA LX,FFM_INV_EXTR,2.048780
39630,201812,22006,FI,US9128284J61,BEBCE,US9128284J61,FI_INV_EXTR,8483.650407
39631,201812,22006,FI,US9128284Y39,BEBCE,US9128284Y39,FI_INV_EXTR,2852.439024
39632,201812,22006,FI,US912828F627,BEBCE,US912828F627,FI_INV_EXTR,8416.577236
39633,201812,22011,FI,SANHYDI LX,ETFA,SANHYDI LX,FI_INV_EXTR,46664.707317
39634,201812,22013,FI,CFIE ACPPD2U,CFIE,CFIE ACPPD2U,FI_INV_EXTR,26401.260000
39635,201812,22017,FM,XS1867930999,NEERV,XS1867930999,FFM_INV_EXTR,17742.845528
39636,201812,22018,FM,XS1836387933,NEERV,XS1836387933,FFM_INV_EXTR,28473.081301
39637,201812,22021,FI,SCHEMCA LX,CFME,SCHEMCA LX,FI_INV_EXTR,1090.167561
39638,201812,22021,FI,SCHECAC LX,CFME,SCHECAC LX,FI_INV_EXTR,4507.532195
39639,201812,22021,FI,VONFARJ LX,CFME,VONFARJ LX,FI_INV_EXTR,2835.565366
39640,201812,22021,FI,GUIASIA LX,CFME,GUIASIA LX,FI_INV_EXTR,3818.410732
39641,201812,22021,FI,MATAPTI LX,CFME,MATAPTI LX,FI_INV_EXTR,2925.941951
39642,201812,22021,FI,EWZ US,ETFA,EWZ US,FI_INV_EXTR,2208.577805
39643,201812,22021,FI,EZA US,ETFA,EZA US,FI_INV_EXTR,1508.159268
39644,201812,22021,FI,EWW US,ETFA,EWW US,FI_INV_EXTR,593.096341
39645,201812,22021,FI,EEM US,ETFA,EEM US,FI_INV_EXTR,5738.913171
39646,201812,22021,FI,ILF US,ETFA,ILF US,FI_INV_EXTR,1095.816098
39647,201812,22021,FI,AAXJ US,ETFA,AAXJ US,FI_INV_EXTR,8902.093659
39648,201812,22021,FI,ERUS US,ETFA,ERUS US,FI_INV_EXTR,316.318049
39649,201812,22022,FI,TRPGEBI LX,CFME,TRPGEBI LX,FI_INV_EXTR,12257.324390
39650,201812,22022,FI,TRPELMI LX,CFME,TRPELMI LX,FI_INV_EXTR,6168.201951
39651,201812,22022,FI,TRPEMCI LX,CFME,TRPEMCI LX,FI_INV_EXTR,12234.730244
39652,201812,22029,FI,CHILEANFEEDER,OTDNE,CHILEANFEEDER,FI_INV_EXTR,70990.807805
39653,201812,22039,FI,OTRO,OTROC,OTRO,FI_INV_EXTR,4066.946341
39654,201812,22040,FI,PRPRONOTE,OTROC,PRPRONOTE,FI_INV_EXTR,95313.406341

In [15]:
import sqlite3

conn = sqlite3.connect('db_transacciones.db')

query = 'select *  from transacciones limit 1'

df = pd.read_sql(query, conn)

df

,PERIODO,R_INVERSIONISTA,R_TIPO_INVERSIONISTA,R_ACTIVO,R_TIPO_ACTIVO,R_NEMO_ACTIVO,DESTINO,R_MONTO_INVERSION
0,201812,19528,FI,12345,CFIPE,OTRO,FI_INV_EXTR,150705.276423